# Generated by Django 4.0.4 on 2022-09-05 17:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaParceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Compartimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linha', models.IntegerField()),
                ('ordem', models.IntegerField()),
                ('descricao', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Cuidador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='BR')),
                ('crc', models.IntegerField(blank=True, null=True, verbose_name='CRC')),
                ('redes_sociais', models.CharField(blank=True, max_length=255, null=True, verbose_name='Redes Sociais')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.cidade')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_comercial', models.CharField(max_length=100)),
                ('laboratorio', models.CharField(max_length=100, verbose_name='Laboratório')),
                ('principio_ativo', models.CharField(max_length=255, verbose_name='Princípio Ativo')),
                ('dose_diaria_maxima', models.CharField(max_length=500, verbose_name='Dose Diária Máxima')),
                ('forma_farmaceutica', models.CharField(max_length=255, verbose_name='Forma Farmacêutica')),
                ('concentracao', models.CharField(max_length=255, verbose_name='Concetração')),
                ('via_administracao', models.CharField(max_length=255, verbose_name='Via Administração')),
                ('grupo_etario', models.CharField(max_length=255, verbose_name='Grupo Etário')),
                ('tarja', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('sigla', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='ProfissionalSaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='BR')),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereço')),
                ('consultorio', models.CharField(max_length=255, verbose_name='Consultório')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('redes_sociais', models.CharField(blank=True, max_length=255, null=True)),
                ('crc', models.IntegerField(unique=True)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.cidade')),
            ],
        ),
        migrations.CreateModel(
            name='Tratamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_prescricao', models.DateField(verbose_name='Data da Prescrição')),
                ('concetracao', models.FloatField(verbose_name='Concentração')),
                ('frequencia_diaria', models.IntegerField(verbose_name='Frequência Diária')),
                ('horarios_diarios', models.CharField(max_length=255, verbose_name='Horários Diários')),
                ('quantidade_ingerir', models.FloatField()),
                ('unidade_medida', models.CharField(choices=[('mg', 'mg'), ('ml', 'ml'), ('g', 'g'), ('gotas', 'gotas')], max_length=5)),
                ('data_inicio', models.DateField()),
                ('tipo_tratamento', models.CharField(choices=[('continuo', 'Contínuo'), ('temporario', 'Temporário')], max_length=10)),
                ('periodo_tratamento', models.IntegerField(blank=True, null=True, verbose_name='Período de Tratamento(dias)')),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('tempo_alerta', models.IntegerField(default=15, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='Tempo de Alerta(min)')),
                ('observacao', models.TextField(blank=True, max_length=255, null=True, verbose_name='Observação')),
                ('lote', models.IntegerField(blank=True, null=True)),
                ('validade', models.DateField(blank=True, null=True)),
                ('embalagem_fracionavel', models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')])),
                ('quantidade_total_embalagem', models.IntegerField(verbose_name='Quantidade Total de Embalagem')),
                ('amostraGratis', models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')])),
                ('status_tratamento', models.BooleanField(choices=[(True, 'Ativo'), (False, 'Inativo')])),
                ('status_tratamento_data', models.DateTimeField(blank=True, null=True, verbose_name='Data da Atualização de Status')),
                ('cadastrado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField()),
                ('cadastrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cadastrado_por', to=settings.AUTH_USER_MODEL)),
                ('compartimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.compartimento')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.medicamento')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paciente_tratemento', to=settings.AUTH_USER_MODEL)),
                ('prescrito_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.profissionalsaude')),
            ],
        ),
        migrations.CreateModel(
            name='Parceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpfcnpj', models.IntegerField(verbose_name='CPF/CNPJ')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereço')),
                ('telefone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='BR')),
                ('email', models.EmailField(max_length=254)),
                ('redes_sociais', models.CharField(max_length=255)),
                ('categoria_parceiro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.categoriaparceiro')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.cidade')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='BR')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('documento', models.CharField(max_length=14)),
                ('cep', models.CharField(max_length=9)),
                ('bairro', models.CharField(max_length=255)),
                ('logradouro', models.CharField(max_length=255)),
                ('numero', models.IntegerField()),
                ('anamnese', models.FileField(blank=True, null=True, upload_to='')),
                ('redes_sociais', models.CharField(blank=True, max_length=255, null=True, verbose_name='Redes Sociais')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.cidade')),
                ('cuidadores', models.ManyToManyField(to='cadastros.cuidador')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lovebox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(choices=[(True, 'Ativo'), (False, 'Inativo')])),
                ('num_serie', models.IntegerField(verbose_name='Número de Série')),
                ('modelo', models.CharField(max_length=100)),
                ('num_compartimentos', models.CharField(max_length=500, verbose_name='Número de Compartimentos')),
                ('tempo_alerta_geral', models.IntegerField(verbose_name='Tempo de Alerta Geral(min)')),
                ('cuidador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.cuidador')),
                ('parceiro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastros.parceiro')),
                ('proprietario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.paciente', verbose_name='Proprietário')),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('sigla', models.CharField(max_length=2)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.pais')),
            ],
        ),
        migrations.CreateModel(
            name='DosesTratamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lovebox', models.CharField(max_length=100)),
                ('tempo_alerta_especifico', models.IntegerField()),
                ('status_ingestao', models.BooleanField(choices=[(True, 'S'), (False, 'N')], default=False)),
                ('status_sincronizacao_download', models.BooleanField(default=True)),
                ('data_sincronizacao_download', models.DateTimeField(blank=True, null=True)),
                ('status_sincronização_upload', models.BooleanField(blank=True, null=True)),
                ('data_sincronizacao_upload', models.DateTimeField(default=False)),
                ('status_tratamento', models.BooleanField(choices=[(True, 'Ativo'), (False, 'Inativo')], default=True)),
                ('paciente', models.CharField(max_length=255)),
                ('dosagem', models.CharField(max_length=255)),
                ('medicamento', models.CharField(max_length=255)),
                ('tratamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.tratamento')),
            ],
        ),
        migrations.AddField(
            model_name='compartimento',
            name='lovebox',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.lovebox'),
        ),
        migrations.AddField(
            model_name='cidade',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.estado'),
        ),
    ]
