# Generated by Django 4.0.4 on 2022-05-31 14:39

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categoria_parceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cuidador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.IntegerField()),
                ('crc', models.IntegerField(blank=True, null=True)),
                ('redes_sociais', models.CharField(max_length=255)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.cidade')),
            ],
        ),
        migrations.CreateModel(
            name='DosesTratamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('compartimentoCaixa', models.CharField(max_length=2)),
                ('tempoAlertaEspecífico', models.DateTimeField()),
                ('statusIngestão', models.CharField(choices=[('s', 'S'), ('n', 'N')], default='n', max_length=1)),
                ('statusSincronização', models.CharField(choices=[('s', 'S'), ('n', 'N')], default='n', max_length=1)),
                ('statusTratamento', models.CharField(choices=[('s', 'S'), ('n', 'N')], default='s', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Fabricante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_comercial', models.CharField(max_length=100)),
                ('laboratorio', models.CharField(max_length=100, verbose_name='Laboratório')),
                ('principio_ativo', models.CharField(max_length=255, verbose_name='Princípio Ativo')),
                ('dose_diaria_maxima', models.CharField(max_length=500, verbose_name='Dose Diária Máxima')),
                ('forma_farmaceutica', models.CharField(max_length=255, verbose_name='Forma Farmacêutica')),
                ('concentracao', models.CharField(max_length=255, verbose_name='Concetração')),
                ('via_administracao', models.CharField(max_length=255, verbose_name='Via Administração')),
                ('grupo_etario', models.CharField(max_length=255, verbose_name='Grupo Etário')),
                ('tarja', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('sigla', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='ProfissionalSaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.IntegerField()),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereço')),
                ('consultorio', models.CharField(max_length=255, verbose_name='Consultório')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('redes_sociais', models.CharField(max_length=255)),
                ('crc', models.IntegerField(unique=True)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.cidade')),
            ],
        ),
        migrations.CreateModel(
            name='Tratamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_prescricao', models.DateField()),
                ('concetracao', models.FloatField()),
                ('frequencia_diaria', models.IntegerField(verbose_name='Frequência Diária')),
                ('horarios_diarios', models.CharField(max_length=255, verbose_name='Horários Diários')),
                ('quantidade_ingerir', models.FloatField()),
                ('unidade_medida', models.CharField(choices=[('mg', 'mg'), ('ml', 'ml'), ('g', 'g'), ('gotas', 'gotas')], max_length=5)),
                ('data_inicio', models.DateField()),
                ('tipo_tratamento', models.CharField(choices=[('continuo', 'Contínuo'), ('temporario', 'Temporário')], max_length=10)),
                ('periodo_tratamento', models.IntegerField(blank=True, null=True, verbose_name='Período de Tratamento(dias)')),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('observacao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Observação')),
                ('lote', models.IntegerField(blank=True, null=True)),
                ('validade', models.DateField(blank=True, null=True)),
                ('embalagem_fracionavel', models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')])),
                ('quantidade_total_embalagem', models.IntegerField(verbose_name='Quantidade Total de Embalagem')),
                ('amostraGratis', models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')])),
                ('status_tratamento', models.BooleanField(choices=[(True, 'Ativo'), (False, 'Inativo')])),
                ('cadastrado_em', models.DateField()),
                ('atualizado_em', models.DateField()),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.medicamento')),
                ('prescrito_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.profissionalsaude')),
            ],
        ),
        migrations.CreateModel(
            name='Parceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpfcnpj', models.IntegerField(verbose_name='CPF/CNPJ')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereço')),
                ('telefone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('redes_sociais', models.CharField(max_length=255)),
                ('categoria_parceiro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.categoria_parceiro')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.cidade')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='BR')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('documento', models.CharField(max_length=14)),
                ('cep', models.CharField(max_length=9)),
                ('bairro', models.CharField(max_length=255)),
                ('logradouro', models.CharField(max_length=255)),
                ('numero', models.IntegerField()),
                ('anamnese', models.FileField(blank=True, null=True, upload_to='')),
                ('redes_sociais', models.CharField(blank=True, max_length=255, null=True, verbose_name='Redes Sociais')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.cidade')),
            ],
        ),
        migrations.CreateModel(
            name='Notificação',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativa')], max_length=7)),
                ('cuidador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.cuidador')),
                ('dosesTratamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.dosestratamento')),
            ],
        ),
        migrations.CreateModel(
            name='Lovebox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numSerie', models.IntegerField(verbose_name='Número de Série')),
                ('modelo', models.CharField(max_length=100)),
                ('compartimentos', models.CharField(max_length=500)),
                ('tempoAlertaGeral', models.IntegerField()),
                ('cuidador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.cuidador')),
                ('parceiro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.parceiro')),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('sigla', models.CharField(max_length=2)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.pais')),
            ],
        ),
        migrations.AddField(
            model_name='dosestratamento',
            name='tratamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.tratamento'),
        ),
        migrations.AddField(
            model_name='cidade',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.estado'),
        ),
    ]
