# Generated by Django 4.0.4 on 2022-09-05 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dosestratamento',
            name='status_tratamento',
        ),
    ]
