# Generated by Django 4.0.4 on 2022-09-05 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_remove_dosestratamento_data_sincronizacao_download_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dosestratamento',
            name='status_tratamento',
            field=models.BooleanField(choices=[(True, 'Ativo'), (False, 'Inativo')], default=True),
        ),
    ]
