# Generated by Django 4.0.4 on 2022-05-31 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_remove_paciente_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='documento',
            field=models.CharField(default='123', max_length=14),
            preserve_default=False,
        ),
    ]
