# Generated by Django 4.0.4 on 2022-06-02 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_paciente_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissionalsaude',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='profissionalsaude',
            name='redes_sociais',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
