# Generated by Django 4.0.4 on 2022-06-02 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_alter_profissionalsaude_email_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='categoria_parceiro',
            new_name='CategoriaParceiro',
        ),
        migrations.AlterField(
            model_name='cuidador',
            name='telefone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='parceiro',
            name='telefone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='profissionalsaude',
            name='telefone',
            field=models.CharField(max_length=15),
        ),
    ]
