# Generated by Django 4.0.4 on 2022-09-05 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_remove_dosestratamento_data_sincronizacao_download_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dosestratamento',
            name='data_sincronizacao_download',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dosestratamento',
            name='data_sincronizacao_upload',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dosestratamento',
            name='status_sincronizacao_download',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dosestratamento',
            name='status_sincronização_upload',
            field=models.BooleanField(default=False),
        ),
    ]
