# Generated by Django 4.0.4 on 2022-09-09 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0005_dosestratamento_data_sincronizacao_download_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dosestratamento',
            name='horario_dose',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
