# Generated by Django 4.0.4 on 2022-06-02 19:51

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0005_rename_categoria_parceiro_categoriaparceiro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='telefone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='BR'),
        ),
    ]
