# Generated by Django 4.0.4 on 2022-06-02 19:58

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0006_alter_paciente_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuidador',
            name='telefone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='BR'),
        ),
        migrations.AlterField(
            model_name='parceiro',
            name='telefone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='BR'),
        ),
        migrations.AlterField(
            model_name='profissionalsaude',
            name='telefone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='BR'),
        ),
    ]
