# Generated by Django 4.0.4 on 2022-09-14 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0007_dosestratamento_compartimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='dosestratamento',
            name='um',
            field=models.CharField(default='mg', max_length=3),
        ),
    ]
