# Generated by Django 4.0.4 on 2022-06-07 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cadastros', '0007_alter_cuidador_telefone_alter_parceiro_telefone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
