# Generated by Django 4.0.4 on 2022-06-09 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0011_tratamento_cadastrado_por_tratamento_paciente'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='cuidadores',
            field=models.ManyToManyField(to='cadastros.cuidador'),
        ),
    ]
