# Generated by Django 4.0.4 on 2022-06-09 13:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0012_paciente_cuidadores'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dosestratamento',
            old_name='compartimentoCaixa',
            new_name='compartimento_caixa',
        ),
        migrations.RenameField(
            model_name='dosestratamento',
            old_name='statusIngestão',
            new_name='status_ingestão',
        ),
        migrations.RenameField(
            model_name='dosestratamento',
            old_name='statusSincronização',
            new_name='status_sincronização',
        ),
        migrations.RenameField(
            model_name='dosestratamento',
            old_name='statusTratamento',
            new_name='status_tratamento',
        ),
        migrations.RenameField(
            model_name='dosestratamento',
            old_name='tempoAlertaEspecífico',
            new_name='tempo_alerta_específico',
        ),
        migrations.AddField(
            model_name='tratamento',
            name='compartimento',
            field=models.CharField(default='A1', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tratamento',
            name='status_tratamento_data',
            field=models.DateTimeField(default='2020-10-30 15:30'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tratamento',
            name='tempo_alerta',
            field=models.IntegerField(default=15, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='Tempo de Alerta(min)'),
        ),
        migrations.AlterField(
            model_name='tratamento',
            name='atualizado_em',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='tratamento',
            name='cadastrado_em',
            field=models.DateTimeField(),
        ),
    ]
