# Generated by Django 4.0.4 on 2022-06-09 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0013_rename_compartimentocaixa_dosestratamento_compartimento_caixa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tratamento',
            name='data_prescricao',
            field=models.DateTimeField(),
        ),
    ]
