# Generated by Django 4.0.4 on 2022-08-22 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0015_alter_tratamento_data_prescricao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lovebox',
            old_name='compartimentos',
            new_name='num_compartimentos',
        ),
        migrations.RenameField(
            model_name='lovebox',
            old_name='numSerie',
            new_name='num_serie',
        ),
        migrations.RenameField(
            model_name='lovebox',
            old_name='tempoAlertaGeral',
            new_name='tempo_alerta_geral',
        ),
        migrations.RemoveField(
            model_name='dosestratamento',
            name='compartimento_caixa',
        ),
        migrations.RemoveField(
            model_name='dosestratamento',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='dosestratamento',
            name='status_ingestão',
        ),
        migrations.RemoveField(
            model_name='dosestratamento',
            name='status_sincronização',
        ),
        migrations.RemoveField(
            model_name='dosestratamento',
            name='tempo_alerta_específico',
        ),
        migrations.RemoveField(
            model_name='notificação',
            name='cuidador',
        ),
        migrations.RemoveField(
            model_name='notificação',
            name='dosesTratamento',
        ),
        migrations.RemoveField(
            model_name='tratamento',
            name='compartimento',
        ),
        migrations.AddField(
            model_name='dosestratamento',
            name='dosagem',
            field=models.CharField(default='2', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dosestratamento',
            name='lovebox',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dosestratamento',
            name='medicamento',
            field=models.CharField(default='nenhum', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dosestratamento',
            name='paciente',
            field=models.CharField(default='ninguem', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dosestratamento',
            name='status_ingestao',
            field=models.BooleanField(choices=[(True, 'S'), (False, 'N')], default=False),
        ),
        migrations.AddField(
            model_name='dosestratamento',
            name='tempo_alerta_especifico',
            field=models.IntegerField(default=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lovebox',
            name='proprietario',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='cadastros.paciente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lovebox',
            name='status',
            field=models.BooleanField(choices=[(True, 'Ativo'), (False, 'Inativo')], default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dosestratamento',
            name='status_tratamento',
            field=models.BooleanField(choices=[(True, 'Ativo'), (False, 'Inativo')], default=True),
        ),
        migrations.AlterField(
            model_name='tratamento',
            name='observacao',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='tratamento',
            name='status_tratamento_data',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da Atualização de Status'),
        ),
        migrations.CreateModel(
            name='Compartimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linha', models.IntegerField()),
                ('ordem', models.IntegerField()),
                ('descricao', models.CharField(max_length=255)),
                ('lovebox', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.lovebox')),
            ],
        ),
    ]
