# Generated by Django 4.0.4 on 2022-08-22 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0016_rename_compartimentos_lovebox_num_compartimentos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lovebox',
            name='parceiro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastros.parceiro'),
        ),
    ]
